import { useEffect, useMemo, useState } from "react";
import { hostAiApiClient } from "../../api/client";
import type { AICostBreakdown, ArticleCulinaryContext, ArticuloDetalle, ArticuloResumen } from "../../types/articulos";
import { articulosService } from "../../services/articulosService";
import { DraftArticleAi } from "./DraftArticleAi";
import { AiCostSummary, reportAiCost } from "./AiCostSummary";

type Domain = "EVENTO" | "ARTICULO" | "RECETA";
type Operation = "CREAR" | "MODIFICAR" | "ARCHIVAR";
type Props = { domain: Domain; operation: Operation; entityId?: string; initial?: Record<string, unknown>; culinaryContext?: ArticleCulinaryContext; onCancel: () => void; onConfirmed: (record: Record<string, unknown>) => void };
const EMPTY_INITIAL: Record<string, unknown> = {};

const definitions: Record<Domain, Array<{ key: string; label: string; type?: string; required?: boolean }>> = {
  EVENTO: [{ key: "nombre", label: "Nombre", required: true }, { key: "fecha", label: "Fecha", type: "date", required: true }, { key: "hora_inicio", label: "Hora", type: "time" }, { key: "pax", label: "PAX", type: "number", required: true }, { key: "estado", label: "Estado" }, { key: "cliente", label: "Cliente" }, { key: "tipo", label: "Tipo" }, { key: "ubicacion", label: "Ubicación" }, { key: "observaciones", label: "Observaciones" }],
  ARTICULO: [{ key: "nombre", label: "Nombre", required: true }, { key: "codigo", label: "Código / referencia", required: true }, { key: "unidad_base", label: "Unidad base" }, { key: "unidad_compra", label: "Unidad de compra" }, { key: "cantidad_formato", label: "Cantidad por formato", type: "number" }, { key: "unidad_formato", label: "Unidad de formato" }, { key: "precio", label: "Precio", type: "number" }, { key: "proveedor", label: "Proveedor preferente" }, { key: "estado", label: "Estado" }, { key: "observaciones", label: "Observaciones" }],
  RECETA: [{ key: "nombre", label: "Nombre", required: true }, { key: "codigo", label: "Código", required: true }, { key: "numero_raciones", label: "Rendimiento / raciones", type: "number", required: true }, { key: "unidad_rendimiento", label: "Unidad de rendimiento" }, { key: "ingredientes_texto", label: "Ingredientes (uno por línea: nombre | cantidad unidad)", required: true }, { key: "elaboracion", label: "Procedimiento" }, { key: "tiempo_activo", label: "Tiempo activo" }, { key: "tiempo_pasivo", label: "Tiempo pasivo" }, { key: "conservacion", label: "Conservación" }, { key: "alergenos_texto", label: "Alérgenos separados por comas" }, { key: "observaciones", label: "Observaciones" }],
};

export function SafeCatalogWritePanel({ domain, operation, entityId = "", initial = EMPTY_INITIAL, culinaryContext = {}, onCancel, onConfirmed }: Props) {
  const fields = operation === "ARCHIVAR" ? [] : definitions[domain];
  const preparedInitial = useMemo(() => toForm(domain, initial), [domain, initial]);
  const [form, setForm] = useState<Record<string, string>>(preparedInitial);
  const [preview, setPreview] = useState<{ preview_token: string; propuesto: Record<string, unknown> } | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [draftProposals, setDraftProposals] = useState<Record<string, string>>({});
  const [draftProposalEdited, setDraftProposalEdited] = useState<Record<string, boolean>>({});
  const [draftOrigins, setDraftOrigins] = useState<Record<string, "IA" | "USUARIO">>({});
  const [relations, setRelations] = useState<Record<string, ArticuloResumen | null>>(() => initialRelations(initial));
  const [aiCost, setAiCost] = useState<AICostBreakdown | null>(null);
  useEffect(() => { setForm(preparedInitial); setRelations(initialRelations(initial)); setPreview(null); setError(""); }, [preparedInitial, initial]);
  const prepare = async () => { setBusy(true); setError(""); try { const data = operation === "ARCHIVAR" ? {} : payload(domain, form); if (domain === "RECETA" && operation !== "ARCHIVAR") data.ingredientes_estructurados = (data.ingredientes as string[]).map((nombre) => ({ nombre, article_id: relations[nombre]?.id || null, estado: relations[nombre] ? "RESUELTO" : "SIN_VINCULAR" })); setPreview(await (domain === "ARTICULO" && operation === "CREAR" ? hostAiApiClient.previewCatalogCrud(domain, operation, data, entityId, "web", draftOrigins) : hostAiApiClient.previewCatalogCrud(domain, operation, data, entityId))); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo preparar la vista previa."); } finally { setBusy(false); } };
  const proposeDraft = async () => { setBusy(true); setError(""); try { const response = await hostAiApiClient.proposeArticleDraft(payload("ARTICULO", form), culinaryContext); setDraftProposals(Object.fromEntries(Object.entries(response.datos_propuestos_ia).map(([key, value]) => [key, String(value)]))); setAiCost(response.cost_breakdown || null); reportAiCost(response.cost_breakdown); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudieron generar propuestas."); } finally { setBusy(false); } };
  const acceptDraftProposal = (field: string) => { const value = draftProposals[field]; setForm((current) => ({ ...current, [field]: value })); setDraftOrigins((current) => ({ ...current, [field]: draftProposalEdited[field] ? "USUARIO" : "IA" })); setDraftProposals((current) => { const next = { ...current }; delete next[field]; return next; }); };
  const rejectDraftProposal = (field: string) => setDraftProposals((current) => { const next = { ...current }; delete next[field]; return next; });
  const confirm = async () => { if (!preview) return; setBusy(true); setError(""); try { const response = await hostAiApiClient.confirmCatalogCrud(preview.preview_token); onConfirmed(response.registro); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo confirmar la operación."); } finally { setBusy(false); } };
  const verb = operation === "CREAR" ? "Nuevo" : operation === "ARCHIVAR" ? "Archivar" : "Editar";
  const captureHumanEdit = (target: EventTarget & Element) => { const label = target.closest("label")?.textContent || ""; const field = fields.find((item) => label.startsWith(item.label)); if (field && draftOrigins[field.key] === "IA") setDraftOrigins((current) => ({ ...current, [field.key]: "USUARIO" })); };
  return <section className={`menu-editor safe-crud-editor${operation === "ARCHIVAR" ? " danger-zone" : ""}`} aria-label={`${verb} ${domain.toLowerCase()}`} onChangeCapture={(event) => captureHumanEdit(event.target as EventTarget & Element)}>
    <h3>{verb} {labels(domain)}</h3>
    {!preview && domain === "ARTICULO" && operation === "CREAR" ? <DraftArticleAi form={form} busy={busy} proposals={draftProposals} onGenerate={() => void proposeDraft()} onChange={(field, value) => { setDraftProposals((current) => ({ ...current, [field]: value })); setDraftProposalEdited((current) => ({ ...current, [field]: true })); }} onAccept={acceptDraftProposal} onReject={rejectDraftProposal} /> : null}
    <AiCostSummary cost={aiCost} title="Coste de generación" />
    {!preview ? <>{operation === "ARCHIVAR" ? <p>La receta dejará de aparecer en la Biblioteca activa. No se eliminará físicamente.</p> : null}{fields.map((field) => <label key={field.key}>{field.label}{field.key.includes("observaciones") || field.key.includes("elaboracion") || field.key.includes("texto") ? <textarea required={field.required} value={form[field.key] || ""} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })} /> : <input required={field.required} type={field.type || "text"} step={field.type === "number" ? "any" : undefined} value={form[field.key] || ""} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })} />}</label>)}<div className="menu-actions"><button type="button" className={operation === "ARCHIVAR" ? "danger" : undefined} disabled={busy} onClick={() => void prepare()}>{busy ? "Preparando..." : operation === "ARCHIVAR" ? "Revisar archivado" : "Revisar y guardar"}</button><button type="button" className="secondary" onClick={onCancel}>Cancelar</button></div></> : <section className="final-review" aria-label="Vista previa"><h4>Vista previa</h4><p>{operation === "ARCHIVAR" ? "Se va a archivar esta receta." : `Se va a ${operation === "CREAR" ? "crear un nuevo registro" : "guardar esta modificación"}.`}</p><dl>{Object.entries(preview.propuesto).filter(([key]) => !["creado_en", "actualizado_en"].includes(key)).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{display(value)}</dd></div>)}</dl><div className="menu-actions"><button type="button" className={operation === "ARCHIVAR" ? "danger" : undefined} disabled={busy} onClick={() => void confirm()}>{busy ? "Confirmando..." : operation === "ARCHIVAR" ? "Confirmar archivado" : "Confirmar"}</button><button type="button" className="secondary" onClick={() => setPreview(null)}>Volver a editar</button><button type="button" className="secondary" onClick={onCancel}>Cancelar</button></div></section>}
    {!preview && domain === "RECETA" && operation !== "ARCHIVAR" ? <IngredientRelations text={form.ingredientes_texto || ""} recipeName={form.nombre || ""} recipeId={form.codigo || entityId} culinaryUse={form.elaboracion || ""} relations={relations} onChange={setRelations} /> : null}
    {error ? <p role="alert">{error}</p> : null}
  </section>;
}

function labels(domain: Domain) { return domain === "EVENTO" ? "evento" : domain === "ARTICULO" ? "artículo" : "receta"; }
function initialRelations(value: Record<string, unknown>): Record<string, ArticuloResumen | null> { const result: Record<string, ArticuloResumen | null> = {}; for (const raw of Array.isArray(value.ingredientes_estructurados) ? value.ingredientes_estructurados : []) { if (!raw || typeof raw !== "object") continue; const item = raw as Record<string, unknown>; const name = String(item.nombre || item.nombre_original || ""); const id = String(item.article_id || item.articulo_id || ""); if (name && id) result[name] = { id, codigo: String(item.codigo || item.articulo_codigo || id), nombre: String(item.nombre_articulo || item.articulo_nombre || name), estado: "ACTIVO", con_stock: false, tiene_ficha_tecnica: false }; } return result; }
function IngredientRelations({ text, recipeName, recipeId, culinaryUse, relations, onChange }: { text: string; recipeName: string; recipeId: string; culinaryUse: string; relations: Record<string, ArticuloResumen | null>; onChange: (value: Record<string, ArticuloResumen | null>) => void }) {
  const lines = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => { const [name, rawQuantity = ""] = line.split("|").map((value) => value.trim()); const match = rawQuantity.match(/^([\d.,]+)\s*(.*)$/); return { name, quantity: match?.[1] || rawQuantity, unit: match?.[2] || "" }; });
  return <section aria-label="Relaciones de ingredientes"><h4>Artículos vinculados</h4>{lines.map(({ name, quantity, unit }) => <IngredientSearch key={name} name={name} culinaryContext={{ ingrediente_original: name, receta_nombre: recipeName, receta_id: recipeId, uso_culinario: culinaryUse, cantidad_receta: quantity, unidad_receta: unit, procedimiento_receta: culinaryUse }} selected={relations[name]} onSelect={(item) => onChange({ ...relations, [name]: item })} />)}</section>;
}
function IngredientSearch({ name, culinaryContext, selected, onSelect }: { name: string; culinaryContext: ArticleCulinaryContext; selected?: ArticuloResumen | null; onSelect: (value: ArticuloResumen | null) => void }) {
  const [open, setOpen] = useState(false); const [term, setTerm] = useState(name); const [items, setItems] = useState<ArticuloResumen[]>([]); const [busy, setBusy] = useState(false); const [searched, setSearched] = useState(false);
  const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  async function search() { setBusy(true); try { const result = await hostAiApiClient.getArticulos(`?q=${encodeURIComponent(term)}&page_size=10`); setItems(result.catalogo.items); setSearched(true); } finally { setBusy(false); } }
  const generatedCode = `ART-${term.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "").toUpperCase().slice(0, 36) || "NUEVO"}`;
  async function useCreated(record: Record<string, unknown>) {
    try {
      const identity = String(record.id || record.codigo || "");
      const reread = await hostAiApiClient.getArticulos(`?q=${encodeURIComponent(identity)}&page_size=10`);
      const article = reread.catalogo.items.find((item) => item.id === identity || item.codigo === identity);
      if (!article) throw new Error("El artículo se creó, pero la lectura posterior no pudo verificarlo.");
      setItems([article]); onSelect(article); setCreating(false); setSearched(true);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo verificar el artículo creado."); }
  }
  return <article className="recipe-card"><strong>Ingrediente culinario: {name}</strong>{selected ? <><p>Vinculado a: {selected.nombre} <small>{selected.codigo}</small></p><LinkedArticleCompletion articleId={selected.id} culinaryContext={culinaryContext} /></> : <p>{searched && !items.length ? "No se encontró ningún artículo. " : ""}Sin artículo vinculado</p>}<button type="button" className="secondary" onClick={() => setOpen(!open)}>{selected ? "Cambiar artículo" : "Buscar artículo"}</button>{open ? <div><label>Buscar artículo para {name}<input value={term} onChange={(event) => setTerm(event.target.value)} /></label><button type="button" disabled={busy} onClick={() => void search()}>{busy ? "Buscando..." : "Buscar"}</button>{searched && !items.length && !creating ? <button type="button" onClick={() => setCreating(true)}>Crear artículo “{term}”</button> : null}{creating ? <SafeCatalogWritePanel domain="ARTICULO" operation="CREAR" initial={{ nombre: term, codigo: generatedCode }} culinaryContext={culinaryContext} onCancel={() => setCreating(false)} onConfirmed={(record) => void useCreated(record)} /> : null}{items.length > 1 ? <p>Pendiente de confirmar. Candidatos encontrados:</p> : null}<ul>{items.map((item) => <li key={item.id}><label><input type="radio" name={`article-${name}`} checked={selected?.id === item.id} onChange={() => onSelect(item)} />{item.nombre} · {item.codigo}{item.unidad ? ` · ${item.unidad}` : ""}{item.proveedor ? ` · ${item.proveedor}` : ""}</label></li>)}<li><label><input type="radio" name={`article-${name}`} checked={selected === null} onChange={() => onSelect(null)} />Dejar sin vincular</label></li></ul>{error ? <p role="alert">{error}</p> : null}</div> : null}</article>;
}

const ARTICLE_AI_FIELDS = ["familia", "unidad_base", "unidad_compra", "cantidad_formato", "unidad_formato", "observaciones"] as const;
function LinkedArticleCompletion({ articleId, culinaryContext }: { articleId: string; culinaryContext: ArticleCulinaryContext }) {
  const [article, setArticle] = useState<ArticuloDetalle | null>(null); const [proposal, setProposal] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { setArticle(null); setProposal(null); void articulosService.get(articleId).then((response) => setArticle(response.articulo)).catch(() => undefined); }, [articleId]);
  if (!article) return null;
  const missing = ARTICLE_AI_FIELDS.filter((field) => article[field] == null || article[field] === "");
  if (!missing.length) return <p>Ficha de artículo completa.</p>;
  if (!proposal) return <button type="button" onClick={async () => setProposal((await articulosService.proposeDocumentation(articleId, culinaryContext)).datos_propuestos_ia || {})}>Completar artículo con IA</button>;
  return <div><p>Propuestas IA (todavía no guardadas)</p>{Object.entries(proposal).map(([field, value]) => <p key={field}>{field}: {String(value)}</p>)}</div>;
}
function display(value: unknown): string { if (Array.isArray(value)) return value.map(display).join(" · "); if (value && typeof value === "object") return JSON.stringify(value); return String(value ?? "—"); }
function toForm(domain: Domain, value: Record<string, unknown>): Record<string, string> { const result = Object.fromEntries(Object.entries(value).map(([key, item]) => [key, item == null ? "" : String(item)])); if (domain === "RECETA") { result.ingredientes_texto = (Array.isArray(value.ingredientes) ? value.ingredientes : []).map((name, index) => `${name} | ${(Array.isArray(value.cantidades) ? value.cantidades[index] : "") || ""}`).join("\n"); result.alergenos_texto = (Array.isArray(value.alergenos) ? value.alergenos : []).join(", "); } return result; }
function payload(domain: Domain, form: Record<string, string>): Record<string, unknown> { const clean: Record<string, unknown> = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== "")); for (const key of ["pax", "precio", "cantidad_formato", "numero_raciones"]) if (key in clean) clean[key] = Number(clean[key]); if (domain === "RECETA") { const lines = String(clean.ingredientes_texto || "").split(/\r?\n/).map((line) => line.trim()).filter(Boolean); clean.ingredientes = lines.map((line) => line.split("|")[0].trim()); clean.cantidades = lines.map((line) => (line.split("|")[1] || "").trim()); clean.alergenos = String(clean.alergenos_texto || "").split(",").map((item) => item.trim()).filter(Boolean); delete clean.ingredientes_texto; delete clean.alergenos_texto; } return clean; }
