import type { ApiEnvelopeBase } from "./api";

export type CompraDraftLine = { id?: string; nombre: string; articulo_id?: string; cantidad: number; unidad: string; precio_unitario: number; observaciones?: string; propuesta_id?: string };
export type CompraDraft = { id: string; proveedor: string; estado: string; lineas: CompraDraftLine[]; importe_estimado: number; fecha?: string; referencia?: string; observaciones?: string; creado_en: string; actualizado_en: string; recepciones?: Array<{ id: string; estado: string; lineas?: number }>; origen: { tipo: string; id: string; version: number; propuesta_id: string } };
export type CompraValidationIssue = { code: string; field: string; line_index?: number; message: string };
export type CompraDraftRevision = { valido: boolean; errores_bloqueantes: CompraValidationIssue[]; advertencias: CompraValidationIssue[] };
export type CompraDraftResponse = ApiEnvelopeBase & { borrador: CompraDraft; revision?: CompraDraftRevision };
export type CompraDraftInput = { proveedor: string; proveedor_id?: string; fecha?: string; referencia?: string; observaciones?: string; lineas: CompraDraftLine[] };
export type CompraConfirmationResponse = ApiEnvelopeBase & {
  pedido: CompraDraft; borrador: CompraDraft; idempotente: boolean;
  advertencias: CompraValidationIssue[]; stock_modificado: false; inventario_modificado: false; recepciones_creadas: 0;
};
export type ReceptionLine = { order_line_id: string; article_id: string; article_name: string; ordered_quantity: number; previously_received: number; pending_quantity: number; received_quantity: number; unit: string; canonical_unit?: string; stock_quantity?: number | null; order_price: number; received_price: number | null; lot: string; expiry: string; location: string; observations: string; incidences: Array<{ code: string; message: string; bloqueante: boolean }> };
export type ReceptionDocument = { document_id: string; nombre: string; tipo_mime: string; tamano: number; fecha_subida: string; usuario: string; proveedor: string; order_id: string; reception_id: string; referencia: string; fecha_albaran: string; observaciones: string; checksum_sha256: string; estado: "ADJUNTO" | "PENDIENTE_REVISION" | "REVISADO" | "DESCARTADO" };
export type PurchaseReception = { id: string; reception_id: string; order_id: string; proveedor: string; fecha: string; referencia: string; estado: "BORRADOR" | "CONFIRMADA"; actualizado_en: string; lineas: ReceptionLine[]; incidencias: Array<{ code: string; message: string; bloqueante: boolean; order_line_id?: string }>; observaciones: string; confirmable: boolean; document_id?: string; document_name?: string; document_type?: string; document_reference?: string; documento?: ReceptionDocument | null; extraccion_documental?: ReceptionDocumentExtraction | null };
export type PurchaseReceptionResponse = ApiEnvelopeBase & { recepcion: PurchaseReception; idempotente?: boolean; stock_modificado: boolean; pedido?: CompraDraft; movimientos?: Array<Record<string, unknown>> };
export type ReceptionDocumentResponse = ApiEnvelopeBase & { recepcion?: PurchaseReception; documento: ReceptionDocument & { contenido_base64?: string }; idempotente?: boolean; stock_modificado: false };
export type ReceptionExtractionIssue = { code: string; message: string; blocking: boolean };
export type ReceptionExtractionLine = { source_text: string; supplier_article_reference: string; article_name: string; quantity: number; unit: string; unit_price: number; line_total: number; lot: string; expiration_date: string; confidence: number; matched_article_id: string; match_status: "MATCH_EXACTO" | "MATCH_PROPUESTO" | "SIN_MATCH" | "AMBIGUO"; comparison_status: string; candidates: Array<{ article_id: string; name: string; score: number; method: string; unit: string }>; order_line_id: string; ordered_quantity: number; previously_received: number; pending_quantity: number; order_unit: string; order_price: number; price_variation_pct: number | null; issues: ReceptionExtractionIssue[]; accepted: boolean };
export type ReceptionDocumentExtraction = { extraction_id: string; document_id: string; reception_id: string; order_id: string; supplier_name: string; supplier_tax_id: string; supplier_reference: string; delivery_note_number: string; delivery_date: string; order_reference: string; currency: string; subtotal: number; taxes: number; total: number; confidence: number; warnings: string[]; provider_match: { status: string; expected: string; detected: string; confidence: number; issues: ReceptionExtractionIssue[] }; lines: ReceptionExtractionLine[]; issues: ReceptionExtractionIssue[]; method: string; model: string; analyzed_at: string; summary: { detected_lines: number; exact_matches: number; requires_review: number; blocking_issues: number } };
export type ReceptionExtractionResponse = ApiEnvelopeBase & { extraccion: ReceptionDocumentExtraction; propuesta?: ReceptionDocumentExtraction; recepcion: PurchaseReception; stock_modificado: false; confirmada?: false };
