from __future__ import annotations

from typing import Any, Protocol


class CorePublicFacade(Protocol):
    """Contrato de acceso permitido desde API a Core.

    Regla API-01:
    - La API no llama directamente a Produccion, Compras, Stock o Eventos.
    - La API solo consume Executive, Workflow y servicios publicos certificados.
    """

    def health(self) -> dict[str, Any]: ...

    def version(self) -> dict[str, Any]: ...

    def executive(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def dashboard(self, query: dict[str, Any]) -> dict[str, Any]: ...
    def registrar_movimiento_stock(self, body: dict[str, Any]) -> dict[str, Any]: ...

    def eventos(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def workflow(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def plan(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def chat(self, body: dict[str, Any]) -> dict[str, Any]: ...

    def articulos(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def articulo(self, articulo_id: str) -> dict[str, Any]: ...
    def actualizar_articulo(self, articulo_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def revision_stock_produccion(self, plan_id: str) -> dict[str, Any]: ...
    def registrar_stock_desde_produccion(self, plan_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def relacionar_articulo_produccion(self, plan_id: str, body: dict[str, Any]) -> dict[str, Any]: ...

    def biblioteca(self) -> dict[str, Any]: ...

    def elaboraciones(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def elaboracion(self, elaboracion_id: str) -> dict[str, Any]: ...

    def menus(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def menu(self, menu_id: str) -> dict[str, Any]: ...

    def elaboraciones_menu(self, query: dict[str, Any]) -> dict[str, Any]: ...

    def crear_menu(self, body: dict[str, Any]) -> dict[str, Any]: ...

    def actualizar_menu(self, menu_id: str, body: dict[str, Any]) -> dict[str, Any]: ...

    def archivar_menu(self, menu_id: str, body: dict[str, Any]) -> dict[str, Any]: ...

    def crear_importacion_biblioteca(self, body: dict[str, Any]) -> dict[str, Any]: ...

    def importacion_biblioteca(self, importacion_id: str) -> dict[str, Any]: ...

    def propuestas_importacion_biblioteca(self, importacion_id: str) -> dict[str, Any]: ...

    def borrador_importacion_biblioteca(self, importacion_id: str) -> dict[str, Any]: ...

    def actualizar_borrador_importacion_biblioteca(
        self, importacion_id: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...

    def confirmar_importacion_biblioteca(
        self, importacion_id: str, body: dict[str, Any]
    ) -> dict[str, Any]: ...

    def estado_importacion_biblioteca(self, importacion_id: str) -> dict[str, Any]: ...

    def historial_importacion_biblioteca(self, importacion_id: str) -> dict[str, Any]: ...

    def confirmar_borrador_compra(self, pedido_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def crear_borrador_compra_manual(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def crear_recepcion_compra(self, pedido_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def recepcion_compra(self, reception_id: str) -> dict[str, Any]: ...
    def actualizar_recepcion_compra(self, reception_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def confirmar_recepcion_compra(self, reception_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def adjuntar_documento_recepcion_compra(self, reception_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def documento_recepcion_compra(self, reception_id: str) -> dict[str, Any]: ...
    def quitar_documento_recepcion_compra(self, reception_id: str) -> dict[str, Any]: ...
    def crear_plan_produccion_menu(self, menu_id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def plan_produccion(self, plan_id: str) -> dict[str, Any]: ...
    def crear_propuesta_compra_produccion(self, plan_id: str) -> dict[str, Any]: ...
